### ISSUE TITLE
main.css

### ISSUE THREAD

**Issue by Dexus** [LSS-Manager/lss-manager-v3#410]
Ich finde das CSS sollte nicht automatisch das Spiel überschreiben, wenn kein Design genutzt wird. Allgemein finde ich das die CSS die ihr ladet, viel im Spiel unschön gestaltet und teilweise fehlerhaft ist.

Das hier wird geladen wenn aber kein Design ausgewählt wurde. Völlig unnötig weil es das Design verschandelt.
```css
#map_outer {
    border: 0px solid #bdbdbd;
    border-radius: 5px;
    padding: 0;
    margin-left: 0px;
    width: calc(66.66666667% - 30px);
}
```
