### ISSUE TITLE
Einsätze verschwinden nicht mehr

### ISSUE THREAD

**Issue by TomSDEVSN** [LSS-Manager/lss-manager-v3#443]
Durch eine Änderung im CSS/JS, wird nun folgende CSS Class benötigt:
```CSS
.custom_mission_not_shown {
display: none;
}
```
Derzeit ist es nämlich so, dass die Einsätze dadurch nicht mehr verschwinden.
